### ISSUE TITLE
int() is almost useless in Applesoft

### ISSUE THREAD

**Issue by badvision** [neilk/apple-ii-matrix#3]
In Applesoft everything is stored and passed around as a float so using int() might actually just be wasting cycles in some cases.

**Comment by neilk** [comment]
PR welcome if you can make it speed up appreciably. I have no actual Apple II here, only emulation, which is already quite fast enough.

**Comment by badvision** [comment]
1 HOME:POKE 35,25:DIM K(3,2):Z=0:FOR D=0 TO 2:FOR C=0 TO 3:D=1:R=RND(1)*Z:IF R<1 OR K(C,1)>23 THEN K(C,0)=RND(1)*40+1:K(C,1)=0:K(C,2)=INT(RND(1)*2)*96:NEXT C:Z=20:NEXT D
2 K(C,1)=K(C,1)+1:VTAB K(C,1):HTAB K(C,0):PRINT CHR$(RND(1)*K(C,2)+32);:NEXT C,D
